### ISSUE TITLE
Last command is not immediately saved

### ISSUE THREAD

**Issue by petobens** [iloveitaly/ipython-ctrlr-fzf#5]
If as in the GIF I select a command from the history (with enter), run it, and then open the history again then that command is not immediately populated. In my example I would expect the `5000 * 150 * 5` to appear first but i doesn't.

![Peek 2024-02-18 13-01](https://github.com/iloveitaly/ipython-ctrlr-fzf/assets/2583971/e1f5fdc6-df85-4780-a922-becd16161924)

**Comment by iloveitaly** [comment]
Huh! Weird. I don't have time to work on debugging this, but if you're able to figure out a little bit more about the source of the issue I might be able to help you out.
